### ISSUE TITLE
Allow disabling copy | look up | share menu on text select.

### ISSUE THREAD

**Issue by apostopher** [react-native-community/react-native-webview#934]
**Is your feature request related to a problem? If so, Please describe.**

When user long-presses text inside `react-native-wrbview` the default `copy | look up | share` menu appears.

<p align="center">
<img width="361" alt="Screenshot 2019-10-06 at 12 23 57 pm" src="https://user-images.githubusercontent.com/270924/66264243-42501a00-e834-11e9-93c9-d216e12c9523.png">
</p>

**Describe the solutions you came up with**

I tried injecting the following CSS into the HTML page.

```css
*:not(input):not(textarea) {
  -webkit-touch-callout: none !important;
  -webkit-user-select: text !important; // I want to allow users to select text
}
```
but the `copy | look up | share` menu still apprears.

**Additional context**
 
it would be nice to allow `disabling` or `customizing` this menu.
